# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19fef50eef53483772a72a31e0b3dd2a5287334d5018628da744a74469258a55057226c9e15f6166b9c9e512fe50f64d7c620eaed78a81c1f8a14f78714ff136

test:
  secret_key_base: 9cd01de11fc56c30320086c4e8d38ddcec3f3dc05332ef927e87006f4dcb3095977790a6e46cb9889788a2f3d4d85f2e78882eb8afaa346aa5229c5d5d6993a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
